layout_spectrum: 0.6698219827223237
typography_spectrum: 0.271839030651597
color:
  brandStrength: 0.7784110904129978
  lightness: 0.015880396727859826
  saturation: 0.34063363431104565
  rhythmicContrast: 0.9236765171519232
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
coverPrefs:
  filter: false
content_rating:
  adult: false
author:
  name: Lolan Rashid
  email: lolan.rashid@asiaatourism.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7a8dd493-a0fa-456f-9082-5eb176ea866b.png
name: Asia Travel
title: Asia Travel
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/1e4fac80-b251-4a55-b432-28fe06713277.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/1e4fac80-b251-4a55-b432-28fe06713277.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Travel - Tourism - Shipping
purpose:
  - type: contact
    url: 'tel:+9647701539647'
    label: Call +9647701539647
  - type: contact
    url: 'mailto:info@asiaatourism.com'
    label: Contact Us
github: true
